---
- name: INSTALL | Timeshift
  tags:
    - install
  block:
    - name: INSTALL | Install Timeshift from apt repository
      become: true
      ansible.builtin.apt:
        name: timeshift
        state: latest

